### ISSUE TITLE
Fix .clap

### ISSUE THREAD

**Issue by izaakf** [cpssd-students/steely#63]
is broken

**Comment by byxor** [comment]
Get :clap: this :clap: fixed :clap: ASAP! :clap:

**Comment by izaakf** [comment]
We 👏 are 👏 going 👏 to 👏 build 👏 a 👏 wall 👏 and 👏 make 👏 them 👏 pay 👏 for 👏 it!

**Comment by byxor** [comment]
@sentriz Is this fixed?

**Comment by izaakf** [comment]
it doesn't work for things like:
`.                    .`

**Comment by iandioch** [comment]
What's the desired output for `a__b` (ie, multiple spaces between things). Is it:

1.  `a_👏_b` (ie. spaces are joined together)
2. `a_👏_👏_b` (ie. each space gets its own clap)
3. `a_👏__b` (ie. the extra space is kept but there's a clap too)

IMO (1) above looks best, and also has an easy implementation of just splitting the input string by `_`, then joining up all parts of len > 0 with a `_👏_`. No dorty regular expressions.

**Comment by byxor** [comment]
4. `a_👏_b 👏`

**Comment by iandioch** [comment]
Haha

seriously though

**Comment by byxor** [comment]
I am serious. I think the claps should at least be mapped to each word, if not each syllable. Having to subtract 1 feels unnatural to me.
