### ISSUE TITLE
Refactor .gex

### ISSUE THREAD

**Issue by iandioch** [cpssd-students/steely#83]
This craic is a mess. Who wrote this? It's all over the place.

**Comment by byxor** [comment]
https://simpleprogrammer.com/2010/10/01/living-dangerously-refactoring-without-a-safety-net/

**Comment by iandioch** [comment]
Tests would be desirable. I should refactor this code to make it more easily testable.

**Comment by iandioch** [comment]
Good idea.

**Comment by sentriz** [comment]
duplicate of https://github.com/sentriz/steely/issues/84
